---
detectors:
  IrresponsibleModule:
    enabled: false
  UtilityFunction:
    enabled: false
  TooManyStatements:
    max_statements: 10

directories:
  'app/controllers':
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  'app/helpers':
    FeatureEnvy:
      enabled: false
  'app/mailers':
    InstanceVariableAssumption:
      enabled: false
  'app/models':
    InstanceVariableAssumption:
      enabled: false
    Attribute:
      enabled: false

exclude_paths:
  - db
