require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 240
