require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 240

Metrics/MethodLength:
  Max: 20
  Exclude:
    - db/**/*.rb

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
